function [A, B, dt, tt, t_f, t_tau, Rad_2_RPM, x_dim, u_dim, W, V] = sys_init()
%SYS_INIT  Initialize simulation parameters and system dynamics.
%
%   [A, B, dt, tt, t_f, t_tau, Rad_2_RPM, x_dim, u_dim, W, V] = sys_init()
%
%   Purpose:
%       Defines the simulation time base, linearized system dynamics,
%       state and input dimensions, and process/measurement noise models.
%
%   Inputs:
%       None (all parameters are internally defined).
%
%   Outputs:
%       A         - State matrix of linearized quadrotor dynamics
%       B         - Input matrix of linearized quadrotor dynamics
%       dt        - Time step [s]
%       tt        - Time vector [s]
%       t_f       - Final simulation time [s]
%       t_tau     - Control response constant (normalized)
%       Rad_2_RPM - Conversion factor from radians/sec to RPM
%       x_dim     - Number of system states
%       u_dim     - Number of system inputs
%       W         - Process noise covariance
%       V         - Measurement noise covariance
%
%   Notes:
%       - System matrices (A, B) are obtained from Linearize_Quad().
%       - Noise covariances (W, V) are generated by S_Cov(dt).
%
% --------------------------------------------------------------

% ------------- Configuration -------------- %
dt = 0.005; t_f = 10; tt = 0:dt:t_f;         % Time domain
time_const = 10*dt; t_tau = dt/time_const;   % Control response
Rad_2_deg = 360/(2*pi); Rad_2_RPM = 60/(2*pi);

% Linearized system dynamics
[A, B] = Linearize_Quad( ); 
x_dim = size(A, 1);                          % Number of states
u_dim = size(B, 2);                          % Number of inputs

% Covariance matrices (process & measurement)
[W, V] = S_Cov( dt );